version: "3"

services:
    flask-container:
        build: .
        ports:
            - "5000:5000"
        # volumes:
        #     - ./app

    nginx-container:
        image: nginx:latest
        expose:
            - "443"
        ports:
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certificats/cert.pem:/etc/nginx/cert.pem
            - ./certificats/key.pem:/etc/nginx/key.pem
        depends_on:
            - flask-container